baseurl = "https://maurodec.com"
title = "Blog - maurodec.com"
locale = "en-us"
enableRobotsTXT = false

[markup]
  [markup.highlight]
    codeFences = true
    style = "catppuccin-mocha"
    wrapperClass = "code-sample"
    noClasses = true
    lineNos = true
    lineNumbersInTable = true
    tabWidth = 4

[minify]
minifyOutput = true